version: '3.3'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "home-nginx"
    restart: unless-stopped
    volumes:
      - ./certbot/etc:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/log:/var/log/nginx
      - ./docroot/www:/var/www/www
      - ./docroot/blog:/var/www/blog
    ports:
      - 80:80
      - 443:443