version: '3.3'
services:
  certbot:
    image: certbot/certbot
    restart: on-failure:1
    container_name: "home-certbot"
    volumes:
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
      - ./certbot/log:/var/log
      - ./docroot/certbot:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    command: certonly --standalone --email ssolry@gmail.com --agree-tos --no-eff-email --force-renewal -d ${DOMAIN}